[package]
name = "rust_api_design"
version = "0.1.0"
edition = "2024"
description = "Diseño de APIs en Rust para ingenieros de software."
license = "MIT OR Apache-2.0"
repository = "https://github.com/jeresoftx/rust-api-design"
readme = "README.md"
keywords = ["api", "rust", "rest", "design"]
categories = ["web-programming"]

[dependencies]

[[example]]
name = "01-contratos-y-limites"
path = "examples/soluciones/01-contratos-y-limites.rs"

[[example]]
name = "02-rest-y-http-solucion"
path = "examples/soluciones/02-rest-y-http.rs"

[[example]]
name = "03-experiencia-del-consumidor-solucion"
path = "examples/soluciones/03-experiencia-del-consumidor.rs"

[[example]]
name = "04-versionado-y-compatibilidad-solucion"
path = "examples/soluciones/04-versionado-y-compatibilidad.rs"

[[example]]
name = "05-contratos-ejecutables-solucion"
path = "examples/soluciones/05-contratos-ejecutables.rs"

[[example]]
name = "06-estilos-alternativos-solucion"
path = "examples/soluciones/06-estilos-alternativos.rs"

[[example]]
name = "07-operacion-de-apis-solucion"
path = "examples/soluciones/07-operacion-de-apis.rs"

[[example]]
name = "08-identidad-y-acceso-solucion"
path = "examples/soluciones/08-identidad-y-acceso.rs"

[[example]]
name = "09-seguridad-de-apis-solucion"
path = "examples/soluciones/09-seguridad-de-apis.rs"

[[example]]
name = "10-estrategia-gobierno-solucion"
path = "examples/soluciones/10-estrategia-gobierno.rs"
